#!/bin/bash
sudo rm -rf /usr/share/clockenstein/clocks
sudo cp -R clocks /usr/share/clockenstein/
sudo rm -rf /usr/lib/python3/dist-packages/clockenstein
sudo cp -R clockenstein /usr/lib/python3/dist-packages/
sudo mkdir -p /usr/share/clockenstein/sounds
sudo cp data/notification.oga /usr/share/clockenstein/sounds/
killall clockenstein-clocks 2>/dev/null
clockenstein-clocks &
